# Generated by Django 4.0.3 on 2022-10-28 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_data', '0002_alter_desktop_status_alter_laptop_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('type_of_event', models.CharField(max_length=200)),
                ('Audience', models.CharField(choices=[('Faculty', 'Faculty'), ('Student', 'Student'), ('Both', 'Faculty and Student')], max_length=20)),
                ('Organized_by', models.CharField(max_length=255)),
                ('Conducted_by', models.CharField(max_length=255)),
                ('no_of_sponsors', models.IntegerField()),
                ('sponsored_by', models.CharField(max_length=255)),
                ('amt_of_sponsorship', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('no_of_participants', models.IntegerField()),
                ('upload_attendance', models.FileField(upload_to='attendance/event_attendances/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
